package toolgen

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"

	"github.com/signalridge/slipway/internal/engine/capability"
	"github.com/signalridge/slipway/internal/tmpl"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRegistryHasFiveTools(t *testing.T) {
	t.Parallel()
	registry := Registry()
	require.Len(t, registry, 5)

	ids := make([]string, len(registry))
	for i, cfg := range registry {
		ids[i] = cfg.ID
	}
	assert.Equal(t, []string{"claude", "codex", "cursor", "gemini", "opencode"}, ids)
}

func TestResolveTools(t *testing.T) {
	t.Parallel()
	all, err := ResolveTools("all")
	require.NoError(t, err)
	assert.Equal(t, []string{"claude", "codex", "cursor", "gemini", "opencode"}, all)

	none, err := ResolveTools("none")
	require.NoError(t, err)
	assert.Nil(t, none)

	selected, err := ResolveTools("cursor,claude,cursor")
	require.NoError(t, err)
	assert.Equal(t, []string{"claude", "cursor"}, selected)

	_, err = ResolveTools("unknown")
	require.Error(t, err)
}

func TestCommandRegistryContainsAllAdapterSkillIDs(t *testing.T) {
	t.Parallel()
	// Verify registry has 18 commands (5 core + 10 situational + 3 diagnostics).
	assert.Len(t, commandRegistry, 18)

	// Verify all registry entries have the required fields.
	for _, def := range commandRegistry {
		assert.NotEmpty(t, def.ID, "registry entry missing ID")
		assert.True(t, def.Class.IsValid(), "registry entry %s has invalid Class %q", def.ID, def.Class)
		assert.NotEmpty(t, def.Description, "registry entry %s missing Description", def.ID)
		assert.NotEmpty(t, def.Tier, "registry entry %s missing Tier", def.ID)
		assert.True(t, def.Tier == "core" || def.Tier == "situational" || def.Tier == "diagnostics",
			"registry entry %s has invalid Tier %q", def.ID, def.Tier)
	}

	// Count tiers.
	core, sit, diag := 0, 0, 0
	query, mutation := 0, 0
	for _, def := range commandRegistry {
		switch def.Class {
		case CommandClassQuery:
			query++
		case CommandClassMutation:
			mutation++
		}
		switch def.Tier {
		case "core":
			core++
		case "situational":
			sit++
		case "diagnostics":
			diag++
		}
	}
	assert.Equal(t, 5, core, "expected 5 core commands")
	assert.Equal(t, 10, sit, "expected 10 situational commands")
	assert.Equal(t, 3, diag, "expected 3 diagnostics commands")
	assert.Equal(t, 5, query, "expected 5 query commands")
	assert.Equal(t, 13, mutation, "expected 13 mutation commands")

	// Verify commandIDs() returns sorted list matching adapter skill commands only.
	ids := commandIDs()
	assert.Len(t, ids, 15)
	for i := 1; i < len(ids); i++ {
		assert.True(t, ids[i-1] < ids[i], "commandIDs not sorted: %s >= %s", ids[i-1], ids[i])
	}
}

func TestGovernanceSkillExportsCoverRuntimeRegistry(t *testing.T) {
	t.Parallel()

	exported := map[string]struct{}{}
	for _, name := range GovernanceSkillNames {
		exported[name] = struct{}{}
	}
	for _, name := range TemplatedGovernanceSkillNames {
		exported[name] = struct{}{}
	}

	for _, name := range []string{
		"intake-clarification",
		"research-orchestration",
		"plan-audit",
		"wave-orchestration",
		"tdd-governance",
		"spec-compliance-review",
		"code-quality-review",
		"goal-verification",
		"final-closeout",
	} {
		_, ok := exported[name]
		assert.Truef(t, ok, "runtime governance skill %q is not exported by toolgen", name)
	}
}

func TestDetectExistingTools(t *testing.T) {
	t.Parallel()
	root := t.TempDir()

	// Empty workspace: no tools detected.
	assert.Empty(t, DetectExistingTools(root))

	// Bare .claude/ directory (not generated by slipway): should NOT be detected.
	require.NoError(t, os.MkdirAll(filepath.Join(root, ".claude"), 0o755))
	assert.Empty(t, DetectExistingTools(root), "bare .claude/ should not trigger detection")

	// Create slipway marker skill for claude.
	claudeCfg := toolRegistry["claude"]
	markerPath := filepath.Join(root, SkillPath(claudeCfg, "next"))
	require.NoError(t, os.MkdirAll(filepath.Dir(markerPath), 0o755))
	require.NoError(t, os.WriteFile(markerPath, []byte("marker"), 0o644))
	detected := DetectExistingTools(root)
	assert.Equal(t, []string{"claude"}, detected)

	// Add slipway marker for cursor.
	cursorCfg := toolRegistry["cursor"]
	cursorMarker := filepath.Join(root, SkillPath(cursorCfg, "next"))
	require.NoError(t, os.MkdirAll(filepath.Dir(cursorMarker), 0o755))
	require.NoError(t, os.WriteFile(cursorMarker, []byte("marker"), 0o644))
	detected = DetectExistingTools(root)
	assert.Equal(t, []string{"claude", "cursor"}, detected)
}

func TestResolveWorkspaceTool(t *testing.T) {
	t.Run("env override uses generated adapter", func(t *testing.T) {
		root := t.TempDir()
		writeGeneratedAdapterMarker(t, root, toolRegistry["claude"])
		writeGeneratedAdapterMarker(t, root, toolRegistry["codex"])
		setSlipwayToolEnv(t, "codex")

		cfg := ResolveWorkspaceTool(root)
		assert.Equal(t, "codex", cfg.ID)
	})

	t.Run("env override falls back to automatic selection when adapter missing", func(t *testing.T) {
		root := t.TempDir()
		writeGeneratedAdapterMarker(t, root, toolRegistry["cursor"])
		setSlipwayToolEnv(t, "gemini")

		cfg := ResolveWorkspaceTool(root)
		assert.Equal(t, "cursor", cfg.ID)
	})

	t.Run("single generated adapter wins", func(t *testing.T) {
		root := t.TempDir()
		writeGeneratedAdapterMarker(t, root, toolRegistry["gemini"])

		cfg := ResolveWorkspaceTool(root)
		assert.Equal(t, "gemini", cfg.ID)
	})

	t.Run("multiple generated adapters use registry order", func(t *testing.T) {
		root := t.TempDir()
		writeGeneratedAdapterMarker(t, root, toolRegistry["gemini"])
		writeGeneratedAdapterMarker(t, root, toolRegistry["codex"])

		cfg := ResolveWorkspaceTool(root)
		assert.Equal(t, "codex", cfg.ID)
	})

	t.Run("no generated adapters falls back to claude", func(t *testing.T) {
		root := t.TempDir()

		cfg := ResolveWorkspaceTool(root)
		assert.Equal(t, "claude", cfg.ID)
	})
}

func TestHasGeneratedAdapter(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	assert.False(t, hasGeneratedAdapter(root, toolRegistry["claude"]))

	writeGeneratedAdapterMarker(t, root, toolRegistry["claude"])
	assert.True(t, hasGeneratedAdapter(root, toolRegistry["claude"]))
	assert.False(t, hasGeneratedAdapter(root, toolRegistry["cursor"]))
}

func TestGenerateProducesAllExpectedFiles(t *testing.T) {
	root := t.TempDir()
	t.Setenv("CODEX_HOME", t.TempDir())
	require.NoError(t, Generate(root, []string{"claude", "cursor", "codex", "gemini", "opencode"}, true))

	for _, toolID := range []string{"claude", "cursor", "codex", "gemini", "opencode"} {
		cfg := toolRegistry[toolID]

		// Adapter skills (all rendered from templates)
		for _, id := range adapterSkillIDs {
			path := filepath.Join(root, cfg.SkillsDir, "slipway", id, "SKILL.md")
			_, err := os.Stat(path)
			assert.NoError(t, err, "%s: missing adapter skill %s", toolID, id)
		}

		// Governance skills (static) + standalone governance guidance skills
		allStaticGov := append([]string{}, GovernanceSkillNames...)
		allStaticGov = append(allStaticGov, standaloneGovernanceNames...)
		for _, name := range allStaticGov {
			path := filepath.Join(root, cfg.SkillsDir, "slipway", name, "SKILL.md")
			_, err := os.Stat(path)
			assert.NoError(t, err, "%s: missing governance skill %s", toolID, name)
		}

		// Templated governance skills (tool-aware)
		for _, name := range TemplatedGovernanceSkillNames {
			path := filepath.Join(root, cfg.SkillsDir, "slipway", name, "SKILL.md")
			_, err := os.Stat(path)
			assert.NoError(t, err, "%s: missing templated governance skill %s", toolID, name)
		}

		// Command entries — per-tool path and format assertions
		if cfg.CommandsDir != "" {
			ext := ".md"
			if cfg.CommandFormat == "toml" {
				ext = ".toml"
			}
			for _, id := range commandIDs() {
				var path string
				switch cfg.CommandStyle {
				case "flat":
					path = filepath.Join(root, cfg.CommandsDir, "slipway-"+id+ext)
				default:
					path = filepath.Join(root, cfg.CommandsDir, "slipway", id+ext)
				}
				_, err := os.Stat(path)
				assert.NoError(t, err, "%s: missing command entry %s", toolID, id)
			}
		} else {
			// Codex: no project-local commands
			commandsDir := filepath.Join(root, "."+toolID, "commands")
			_, err := os.Stat(commandsDir)
			assert.True(t, os.IsNotExist(err), "%s: unexpected commands directory generated", toolID)
		}

		// Technique skills
		for _, name := range techniqueNames {
			path := filepath.Join(root, cfg.SkillsDir, "slipway", name, "SKILL.md")
			_, err := os.Stat(path)
			assert.NoError(t, err, "%s: missing technique %s", toolID, name)
		}

		// Catalog skills (registry-owned). Every exported catalog skill
		// must carry the adapter-visible frontmatter contract (`name`,
		// `description`) and keep its support artifacts (provenance.yaml)
		// next to SKILL.md so `provenance_ref` is not dangling.
		reg := capability.DefaultRegistry()
		for _, id := range catalogSkillIDs {
			skillDir := filepath.Join(root, cfg.SkillsDir, "slipway", id)
			skillPath := filepath.Join(skillDir, "SKILL.md")
			body, err := os.ReadFile(skillPath)
			assert.NoError(t, err, "%s: missing catalog skill %s", toolID, id)

			fm := extractAdapterFrontmatter(t, string(body), toolID, id)
			assert.Equal(t, "slipway-"+id, fm["name"],
				"%s: catalog skill %s: wrong name", toolID, id)
			assert.NotEmpty(t, fm["description"],
				"%s: catalog skill %s: empty description", toolID, id)
			sk, ok := reg.Lookup(id)
			if assert.Truef(t, ok, "%s: catalog skill %s missing from registry", toolID, id) {
				assert.Equal(t, sk.Summary, fm["description"],
					"%s: catalog skill %s: description drifted from registry summary", toolID, id)
			}

			provPath := filepath.Join(skillDir, "provenance.yaml")
			_, err = os.Stat(provPath)
			assert.NoErrorf(t, err, "%s: catalog skill %s missing provenance.yaml next to SKILL.md", toolID, id)
		}

		// Outbound catalog manifest
		manifestPath := filepath.Join(root, CatalogManifestPath(cfg))
		manifestBytes, err := os.ReadFile(manifestPath)
		assert.NoError(t, err, "%s: missing catalog manifest", toolID)
		assert.Contains(t, string(manifestBytes), "# Using the Slipway Catalog",
			"%s: manifest missing header", toolID)
		assert.Contains(t, string(manifestBytes), "## Triage index",
			"%s: manifest missing triage index", toolID)

		if cfg.SessionHook != "" {
			hookPath := filepath.Join(root, cfg.SessionHook)
			_, err := os.Stat(hookPath)
			assert.NoError(t, err, "%s: missing session-start hook", toolID)
		} else {
			hookPath := filepath.Join(root, "."+toolID, "hooks", "slipway-session-start.sh")
			_, err := os.Stat(hookPath)
			assert.True(t, os.IsNotExist(err), "%s: unexpected session hook generated", toolID)
		}

		switch {
		case cfg.PostToolHook != "":
			hookPath := filepath.Join(root, cfg.PostToolHook)
			_, err := os.Stat(hookPath)
			assert.NoError(t, err, "%s: missing post-tool hook", toolID)

			settingsPath := filepath.Join(root, cfg.SettingsPath)
			content, err := os.ReadFile(settingsPath)
			assert.NoError(t, err, "%s: missing hook settings", toolID)
			settings := string(content)
			assert.Contains(t, settings, cfg.PostToolEvent, "%s: missing post-tool event registration", toolID)
		case cfg.SettingsPath != "":
			settingsPath := filepath.Join(root, cfg.SettingsPath)
			content, err := os.ReadFile(settingsPath)
			assert.NoError(t, err, "%s: missing settings file", toolID)
			settings := string(content)
			assert.Contains(t, settings, "SessionStart", "%s: missing session-start registration", toolID)
			assert.NotContains(t, settings, "slipway-context-monitor", "%s: unexpected post-tool registration", toolID)
		default:
			settingsPath := filepath.Join(root, "."+toolID, "settings.json")
			_, err := os.Stat(settingsPath)
			assert.True(t, os.IsNotExist(err), "%s: unexpected settings file generated", toolID)
		}
	}
}

func TestRenderCatalogSkillUsesFixedTypedTemplateOrder(t *testing.T) {
	t.Parallel()

	skill := capability.Skill{
		ID: "_test-catalog-assembler",
		Bindings: []capability.Binding{
			{Attachment: capability.AttachmentProcedure},
			{Attachment: capability.AttachmentChecklist},
			{Attachment: capability.AttachmentReportSchema},
		},
	}

	content, err := renderCatalogSkill(skill)
	require.NoError(t, err)

	bodyIdx := regexp.MustCompile("BODY_SECTION").FindStringIndex(content)
	proseIdx := regexp.MustCompile("PROSE_SECTION").FindStringIndex(content)
	checklistIdx := regexp.MustCompile("CHECKLIST_SECTION").FindStringIndex(content)
	verdictIdx := regexp.MustCompile("VERDICT_SECTION").FindStringIndex(content)
	require.NotNil(t, bodyIdx)
	require.NotNil(t, proseIdx)
	require.NotNil(t, checklistIdx)
	require.NotNil(t, verdictIdx)
	assert.Less(t, bodyIdx[0], proseIdx[0])
	assert.Less(t, proseIdx[0], checklistIdx[0])
	assert.Less(t, checklistIdx[0], verdictIdx[0])
}

func TestRenderCatalogSkillPreservesSingleFileWhenNoTypedTemplates(t *testing.T) {
	t.Parallel()

	reg := capability.DefaultRegistry()
	skill, ok := reg.Lookup("scope-clarification")
	require.True(t, ok)

	content, err := renderCatalogSkill(skill)
	require.NoError(t, err)

	raw, err := tmpl.Content(filepath.ToSlash(filepath.Join("skills", "scope-clarification", "SKILL.md")))
	require.NoError(t, err)

	// Output equals the source body with the adapter-frontmatter header
	// prepended; no typed-template sections are appended.
	injected, err := injectAdapterFrontmatter(raw, skill)
	require.NoError(t, err)
	assert.Equal(t, injected, content)
}

func TestInjectAdapterFrontmatterPrependsNameAndDescription(t *testing.T) {
	t.Parallel()

	src := "---\nskill_id: demo\nsummary: \"Use when X. Triggers on Y.\"\n---\n\n# Body\n"
	sk := capability.Skill{ID: "demo", Summary: "Use when X. Triggers on Y."}

	out, err := injectAdapterFrontmatter(src, sk)
	require.NoError(t, err)

	// Header lines appear before existing fields.
	nameAt := strings.Index(out, "name: slipway-demo")
	descAt := strings.Index(out, "description: \"Use when X. Triggers on Y.\"")
	skillIDAt := strings.Index(out, "skill_id: demo")
	bodyAt := strings.Index(out, "# Body")
	require.GreaterOrEqual(t, nameAt, 0)
	require.GreaterOrEqual(t, descAt, 0)
	require.GreaterOrEqual(t, skillIDAt, 0)
	require.GreaterOrEqual(t, bodyAt, 0)
	assert.Less(t, nameAt, descAt)
	assert.Less(t, descAt, skillIDAt)
	assert.Less(t, skillIDAt, bodyAt)
}

func TestInjectAdapterFrontmatterEscapesDoubleQuotes(t *testing.T) {
	t.Parallel()

	src := "---\nskill_id: demo\n---\n\nbody\n"
	sk := capability.Skill{ID: "demo", Summary: `needs "quote" and \backslash`}

	out, err := injectAdapterFrontmatter(src, sk)
	require.NoError(t, err)
	assert.Contains(t, out, `description: "needs \"quote\" and \\backslash"`)
}

func TestInjectAdapterFrontmatterRejectsMissingDelimiter(t *testing.T) {
	t.Parallel()

	_, err := injectAdapterFrontmatter("no frontmatter here", capability.Skill{ID: "x"})
	assert.Error(t, err)
}

func TestRenderCatalogSkillUsesTypedTemplatesForProductionSkill(t *testing.T) {
	t.Parallel()

	reg := capability.DefaultRegistry()
	skill, ok := reg.Lookup("independent-review")
	require.True(t, ok)

	content, err := renderCatalogSkill(skill)
	require.NoError(t, err)

	raw, err := tmpl.Content(filepath.ToSlash(filepath.Join("skills", "independent-review", "SKILL.md")))
	require.NoError(t, err)

	// This asserts production catalog assembly actually uses optional typed
	// templates, not only the dedicated test fixture.
	assert.NotEqual(t, raw, content)
	assert.Contains(t, content, "## Procedure")
	assert.Contains(t, content, "## Checklist")
	assert.Contains(t, content, "## Report schema")
}

func TestGeneratedAdapterSurfacesStayInSyncWithRegistry(t *testing.T) {
	root := t.TempDir()
	codexHome := t.TempDir()
	t.Setenv("CODEX_HOME", codexHome)

	toolIDs, err := ResolveTools("all")
	require.NoError(t, err)
	require.NoError(t, Generate(root, toolIDs, true))

	for _, cfg := range Registry() {
		for _, id := range commandIDs() {
			_, absPath := commandSurfacePath(root, codexHome, cfg, id)
			content, err := os.ReadFile(absPath)
			require.NoError(t, err, "missing generated command surface for %s/%s", cfg.ID, id)

			s := string(content)
			assert.Contains(t, s, commandDescriptions[id], "%s/%s missing registry description", cfg.ID, id)
			if cfg.PromptsStyle == "global" {
				assert.Contains(t, s, "slipway-"+id, "%s/%s missing prompt command name", cfg.ID, id)
			} else {
				assert.Contains(t, s, commandTrigger(cfg, id), "%s/%s missing registry trigger", cfg.ID, id)
			}
		}

		if cfg.SettingsPath != "" && cfg.SessionHook != "" {
			assertHookCommandRegistered(
				t,
				filepath.Join(root, cfg.SettingsPath),
				cfg.SessionEvent,
				`bash "`+filepath.ToSlash(cfg.SessionHook)+`"`,
			)
		}
		if cfg.SettingsPath != "" && cfg.PostToolHook != "" {
			assertHookCommandRegistered(
				t,
				filepath.Join(root, cfg.SettingsPath),
				cfg.PostToolEvent,
				`node "`+filepath.ToSlash(cfg.PostToolHook)+`"`,
			)
		}
	}
}

// extractAdapterFrontmatter reads a minimal adapter contract from a
// generated SKILL.md: the set of `key: value` pairs inside the leading
// `---` / `---` frontmatter block. It tolerates double-quoted values and
// ignores nested YAML (lists, maps), which are not part of the adapter
// contract.
func extractAdapterFrontmatter(t *testing.T, raw, toolID, skillID string) map[string]string {
	t.Helper()
	require.Truef(t, len(raw) >= 4 && raw[:4] == "---\n",
		"%s: catalog skill %s: missing frontmatter opener", toolID, skillID)
	rest := raw[4:]
	end := indexOf(rest, "\n---")
	require.GreaterOrEqualf(t, end, 0,
		"%s: catalog skill %s: missing frontmatter closer", toolID, skillID)
	out := map[string]string{}
	for _, line := range splitLines(rest[:end]) {
		// Only scan flat top-level `key: value` pairs. Lines that start
		// with whitespace or `-` belong to nested structures.
		if line == "" || line[0] == ' ' || line[0] == '\t' || line[0] == '-' {
			continue
		}
		colon := indexOf(line, ":")
		if colon <= 0 {
			continue
		}
		key := line[:colon]
		value := ""
		if colon+1 < len(line) {
			value = strings.TrimSpace(line[colon+1:])
		}
		if len(value) >= 2 && value[0] == '"' && value[len(value)-1] == '"' {
			value = value[1 : len(value)-1]
		}
		out[key] = value
	}
	return out
}

func indexOf(s, sub string) int { return strings.Index(s, sub) }
func splitLines(s string) []string {
	return strings.Split(s, "\n")
}

func writeGeneratedAdapterMarker(t *testing.T, root string, cfg ToolConfig) {
	t.Helper()

	markerPath := filepath.Join(root, SkillPath(cfg, "next"))
	require.NoError(t, os.MkdirAll(filepath.Dir(markerPath), 0o755))
	require.NoError(t, os.WriteFile(markerPath, []byte("marker"), 0o644))
}

func setSlipwayToolEnv(t *testing.T, value string) {
	t.Helper()

	original, hadOriginal := os.LookupEnv("SLIPWAY_TOOL")
	require.NoError(t, os.Setenv("SLIPWAY_TOOL", value))
	t.Cleanup(func() {
		if hadOriginal {
			_ = os.Setenv("SLIPWAY_TOOL", original)
			return
		}
		_ = os.Unsetenv("SLIPWAY_TOOL")
	})
}

func TestGeneratedSkillsReferenceValidCommands(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"claude"}, true))

	// Build set of valid commands.
	validCmds := map[string]bool{
		"new": true, "next": true, "run": true, "status": true, "done": true,
		"abort": true, "cancel": true, "review": true, "validate": true, "validate-requirements": true,
		"pivot": true, "preset": true, "repair": true, "init": true, "checkpoint": true,
	}

	// Pattern to find `slipway <cmd>` references in generated files.
	re := regexp.MustCompile("`slipway ([a-z][a-z-]*)`")

	cfg := toolRegistry["claude"]
	allSkillIDs := append([]string(nil), adapterSkillIDs...)
	allSkillIDs = append(allSkillIDs, GovernanceSkillNames...)
	allSkillIDs = append(allSkillIDs, standaloneGovernanceNames...)
	allSkillIDs = append(allSkillIDs, TemplatedGovernanceSkillNames...)
	allSkillIDs = append(allSkillIDs, techniqueNames...)

	for _, id := range allSkillIDs {
		path := filepath.Join(root, cfg.SkillsDir, "slipway", id, "SKILL.md")
		content, err := os.ReadFile(path)
		if err != nil {
			continue // skip if file doesn't exist
		}

		matches := re.FindAllStringSubmatch(string(content), -1)
		for _, m := range matches {
			cmd := m[1]
			// Allow `slipway next --json` style references (extract base command).
			assert.True(t, validCmds[cmd],
				"skill %q references unknown command `slipway %s`", id, cmd)
		}

		// Verify no `slipway advance` references remain (D4 validation).
		assert.NotContains(t, string(content), "slipway advance",
			"skill %q still references retired `slipway advance`", id)
	}
}

func TestGenerateDeterministicAndRefresh(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"claude"}, false))

	skillPath := filepath.Join(root, ".claude", "skills", "slipway/new/SKILL.md")
	commandPath := filepath.Join(root, ".claude", "commands", "slipway", "new.md")
	firstSkill, err := os.ReadFile(skillPath)
	require.NoError(t, err)
	firstCommand, err := os.ReadFile(commandPath)
	require.NoError(t, err)

	// Non-refresh generation should keep existing files unchanged.
	require.NoError(t, os.WriteFile(skillPath, []byte("custom"), 0o644))
	require.NoError(t, Generate(root, []string{"claude"}, false))
	secondSkill, err := os.ReadFile(skillPath)
	require.NoError(t, err)
	assert.Equal(t, "custom", string(secondSkill))

	// Refresh should deterministically regenerate content.
	require.NoError(t, Generate(root, []string{"claude"}, true))
	refreshedSkill, err := os.ReadFile(skillPath)
	require.NoError(t, err)
	refreshedCommand, err := os.ReadFile(commandPath)
	require.NoError(t, err)
	assert.Equal(t, string(firstSkill), string(refreshedSkill))
	assert.Equal(t, string(firstCommand), string(refreshedCommand))
}

func TestGenerateRefreshRemovesRetiredCommandArtifacts(t *testing.T) {
	root := t.TempDir()
	codexHome := t.TempDir()
	t.Setenv("CODEX_HOME", codexHome)

	require.NoError(t, Generate(root, []string{"claude", "codex"}, true))

	staleSkill := filepath.Join(root, ".claude", "skills", "slipway", "sync", "SKILL.md")
	staleCommand := filepath.Join(root, ".claude", "commands", "slipway", "sync.md")
	stalePrompt := filepath.Join(codexHome, "prompts", "slipway-sync.md")
	require.NoError(t, os.MkdirAll(filepath.Dir(staleSkill), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Dir(staleCommand), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Dir(stalePrompt), 0o755))
	require.NoError(t, os.WriteFile(staleSkill, []byte("stale sync skill"), 0o644))
	require.NoError(t, os.WriteFile(staleCommand, []byte("stale sync command"), 0o644))
	require.NoError(t, os.WriteFile(stalePrompt, []byte("stale sync prompt"), 0o644))

	require.NoError(t, Generate(root, []string{"claude", "codex"}, true))

	_, err := os.Stat(staleSkill)
	assert.True(t, os.IsNotExist(err), "refresh should remove retired sync skill surface")
	_, err = os.Stat(staleCommand)
	assert.True(t, os.IsNotExist(err), "refresh should remove retired sync command entry")
	_, err = os.Stat(stalePrompt)
	assert.True(t, os.IsNotExist(err), "refresh should remove retired sync codex prompt")

	_, err = os.Stat(filepath.Join(root, ".claude", "skills", "slipway", "validate-requirements", "SKILL.md"))
	assert.NoError(t, err, "current validate-requirements skill should remain present")
	_, err = os.Stat(filepath.Join(root, ".claude", "commands", "slipway", "validate-requirements.md"))
	assert.NoError(t, err, "current validate-requirements command entry should remain present")
	_, err = os.Stat(filepath.Join(codexHome, "prompts", "slipway-validate-requirements.md"))
	assert.NoError(t, err, "current validate-requirements codex prompt should remain present")
}

func TestCodexAgentTOMLGeneration(t *testing.T) {
	root := t.TempDir()
	t.Setenv("CODEX_HOME", t.TempDir())
	require.NoError(t, Generate(root, []string{"codex"}, true))

	// Check TOML agent files exist.
	for _, name := range []string{"slipway-executor", "slipway-reviewer", "slipway-verifier"} {
		path := filepath.Join(root, ".codex", "agents", name+".toml")
		content, err := os.ReadFile(path)
		require.NoError(t, err, "missing codex agent %s", name)

		s := string(content)
		assert.Contains(t, s, "sandbox_mode = ", "%s: missing sandbox_mode", name)
		assert.Contains(t, s, "developer_instructions = ", "%s: missing developer_instructions", name)
	}

	// Verify sandbox_mode per agent role.
	executorContent, _ := os.ReadFile(filepath.Join(root, ".codex", "agents", "slipway-executor.toml"))
	assert.Contains(t, string(executorContent), `sandbox_mode = "workspace-write"`)
	assert.Contains(t, string(executorContent), "Agent status: manual-only helper.")

	reviewerContent, _ := os.ReadFile(filepath.Join(root, ".codex", "agents", "slipway-reviewer.toml"))
	assert.Contains(t, string(reviewerContent), `sandbox_mode = "read-only"`)
	assert.Contains(t, string(reviewerContent), "Agent status: governance-mapped.")

	verifierContent, _ := os.ReadFile(filepath.Join(root, ".codex", "agents", "slipway-verifier.toml"))
	assert.Contains(t, string(verifierContent), `sandbox_mode = "read-only"`)

	// Check config.toml registration.
	configContent, err := os.ReadFile(filepath.Join(root, ".codex", "config.toml"))
	require.NoError(t, err)
	cs := string(configContent)
	assert.Contains(t, cs, "[agents.slipway-executor]")
	assert.Contains(t, cs, `config_file = "agents/slipway-executor.toml"`)
	assert.Contains(t, cs, "manual-only helper")
	assert.Contains(t, cs, "# BEGIN slipway agents")
	assert.Contains(t, cs, "# END slipway agents")
}

func TestGeminiTOMLCommandFormat(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"gemini"}, true))

	// Gemini commands should use .toml extension.
	path := filepath.Join(root, ".gemini", "commands", "slipway", "new.toml")
	content, err := os.ReadFile(path)
	require.NoError(t, err)

	s := string(content)
	assert.Contains(t, s, `description = "`)
	assert.Contains(t, s, `prompt = """`)

	// No .md command files should exist.
	mdPath := filepath.Join(root, ".gemini", "commands", "slipway", "new.md")
	_, err = os.Stat(mdPath)
	assert.True(t, os.IsNotExist(err), "gemini should not have .md command files")
}

func TestHookSettingsRegistrationForClaudeAndGemini(t *testing.T) {
	root := t.TempDir()
	t.Setenv("CODEX_HOME", t.TempDir())
	require.NoError(t, Generate(root, []string{"claude", "gemini"}, true))

	claudeSettings, err := os.ReadFile(filepath.Join(root, ".claude", "settings.json"))
	require.NoError(t, err)
	assert.Contains(t, string(claudeSettings), "SessionStart")
	assert.Contains(t, string(claudeSettings), "PostToolUse")
	assert.Contains(t, string(claudeSettings), "slipway-session-start.sh")
	assert.Contains(t, string(claudeSettings), "slipway-context-monitor.js")

	geminiSettings, err := os.ReadFile(filepath.Join(root, ".gemini", "settings.json"))
	require.NoError(t, err)
	assert.Contains(t, string(geminiSettings), "SessionStart")
	assert.Contains(t, string(geminiSettings), "AfterTool")
	assert.Contains(t, string(geminiSettings), "slipway-session-start.sh")
	assert.Contains(t, string(geminiSettings), "slipway-context-monitor.js")
}

func TestCommandEntryPrerequisitesAreCommandSpecific(t *testing.T) {
	t.Parallel()

	newEntry, err := renderCommandEntry(toolRegistry["claude"], "new")
	require.NoError(t, err)
	assert.Contains(t, newEntry, "Create a governed change with intake-first workflow")
	assert.Contains(t, newEntry, ".slipway.yaml` must exist")
	assert.NotContains(t, newEntry, "an active change must exist")
	assert.NotContains(t, newEntry, "change intake")

	statusEntry, err := renderCommandEntry(toolRegistry["claude"], "status")
	require.NoError(t, err)
	assert.Contains(t, statusEntry, ".slipway.yaml` must exist")
	assert.NotContains(t, statusEntry, "an active change must exist")

	nextEntry, err := renderCommandEntry(toolRegistry["claude"], "next")
	require.NoError(t, err)
	assert.Contains(t, nextEntry, ".slipway.yaml` must exist")
	assert.Contains(t, nextEntry, "an active change must exist")

	initEntry, err := renderCommandEntry(toolRegistry["gemini"], "init")
	require.NoError(t, err)
	assert.NotContains(t, initEntry, ".slipway.yaml` must exist")
	assert.NotContains(t, initEntry, "an active change must exist")
}

func TestReadmeAndCommandDescriptionsReflectCurrentEntrySurface(t *testing.T) {
	t.Parallel()

	_, filename, _, ok := runtime.Caller(0)
	require.True(t, ok)

	readmePath := filepath.Clean(filepath.Join(filepath.Dir(filename), "..", "..", "README.md"))
	content, err := os.ReadFile(readmePath)
	require.NoError(t, err)
	readme := string(content)

	assert.Contains(t, readme, "`slipway new`")
	assert.Contains(t, readme, "`slipway run`")
	assert.Contains(t, readme, "`slipway validate-requirements`")
	assert.Contains(t, readme, "`artifacts/changes/`")
	assert.Contains(t, readme, "`artifacts/codebase/`")
	assert.NotContains(t, readme, "request intake")
	assert.NotContains(t, readme, "active request resolution")
	assert.NotContains(t, readme, "`openspec/`")
	assert.NotContains(t, readme, "`openspec/`: change and spec artifacts used by governed workflows")

	assert.Equal(t, "Create a governed change with intake-first workflow", commandDescriptions["new"])
	assert.Equal(t, "Advance governed execution until a skill, blocker, checkpoint, or done-ready outcome is surfaced", commandDescriptions["run"])
	assert.Equal(t, "Finalize a done-ready change and archive it", commandDescriptions["done"])
}

func TestCodexPromptsUseCommandSpecificPrerequisites(t *testing.T) {
	root := t.TempDir()
	codexHome := t.TempDir()
	t.Setenv("CODEX_HOME", codexHome)

	require.NoError(t, Generate(root, []string{"codex"}, true))

	newPrompt, err := os.ReadFile(filepath.Join(codexHome, "prompts", "slipway-new.md"))
	require.NoError(t, err)
	assert.NotContains(t, string(newPrompt), "an active change must exist")

	statusPrompt, err := os.ReadFile(filepath.Join(codexHome, "prompts", "slipway-status.md"))
	require.NoError(t, err)
	assert.NotContains(t, string(statusPrompt), "an active change must exist")

	nextPrompt, err := os.ReadFile(filepath.Join(codexHome, "prompts", "slipway-next.md"))
	require.NoError(t, err)
	assert.Contains(t, string(nextPrompt), "an active change must exist")

	initPrompt, err := os.ReadFile(filepath.Join(codexHome, "prompts", "slipway-init.md"))
	require.NoError(t, err)
	assert.NotContains(t, string(initPrompt), ".slipway.yaml` must exist")
}

func TestCodexPromptsIncludeTierAndSurface(t *testing.T) {
	root := t.TempDir()
	codexHome := t.TempDir()
	t.Setenv("CODEX_HOME", codexHome)

	require.NoError(t, Generate(root, []string{"codex"}, true))

	// Core command should have tier: "core".
	newPrompt, err := os.ReadFile(filepath.Join(codexHome, "prompts", "slipway-new.md"))
	require.NoError(t, err)
	assert.Contains(t, string(newPrompt), `class: "mutation"`, "core command prompt missing class metadata")
	assert.Contains(t, string(newPrompt), `tier: "core"`, "core command prompt missing tier metadata")
	assert.Contains(t, string(newPrompt), `surface: "adapter"`, "command prompt missing surface metadata")

	// Query command should preserve class alongside tier and surface metadata.
	statusPrompt, err := os.ReadFile(filepath.Join(codexHome, "prompts", "slipway-status.md"))
	require.NoError(t, err)
	assert.Contains(t, string(statusPrompt), `class: "query"`, "query command prompt missing class metadata")
	assert.Contains(t, string(statusPrompt), `tier: "core"`, "query command prompt missing tier metadata")
	assert.Contains(t, string(statusPrompt), `surface: "adapter"`, "query command prompt missing surface metadata")
}

func TestGeneratedCommandEntriesIncludeClassMetadata(t *testing.T) {
	root := t.TempDir()
	codexHome := t.TempDir()
	t.Setenv("CODEX_HOME", codexHome)

	require.NoError(t, Generate(root, []string{"claude", "gemini", "codex"}, true))

	claudeStatus, err := os.ReadFile(filepath.Join(root, ".claude", "commands", "slipway", "status.md"))
	require.NoError(t, err)
	assert.Contains(t, string(claudeStatus), `class: "query"`)

	geminiRun, err := os.ReadFile(filepath.Join(root, ".gemini", "commands", "slipway", "run.toml"))
	require.NoError(t, err)
	assert.Contains(t, string(geminiRun), `class = "mutation"`)

	codexAbort, err := os.ReadFile(filepath.Join(codexHome, "prompts", "slipway-abort.md"))
	require.NoError(t, err)
	assert.Contains(t, string(codexAbort), `class: "mutation"`)
}

func TestGeneratedWaveOrchestrationSkillUsesDescriptionPlaceholder(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"claude"}, true))

	path := filepath.Join(root, ".claude", "skills", "slipway", "wave-orchestration", "SKILL.md")
	content, err := os.ReadFile(path)
	require.NoError(t, err)

	assert.Contains(t, string(content), "{description}")
	assert.NotContains(t, string(content), "{request_description}")
}

func TestIdempotentConfigTOMLMerge(t *testing.T) {
	root := t.TempDir()
	t.Setenv("CODEX_HOME", t.TempDir())

	// First generation.
	require.NoError(t, Generate(root, []string{"codex"}, true))
	first, err := os.ReadFile(filepath.Join(root, ".codex", "config.toml"))
	require.NoError(t, err)

	// Second generation (refresh).
	require.NoError(t, Generate(root, []string{"codex"}, true))
	second, err := os.ReadFile(filepath.Join(root, ".codex", "config.toml"))
	require.NoError(t, err)

	assert.Equal(t, string(first), string(second), "config.toml should be byte-identical after re-generation")
}

func TestConfigTOMLPreservesUserContent(t *testing.T) {
	root := t.TempDir()
	t.Setenv("CODEX_HOME", t.TempDir())

	// Create a config.toml with user content.
	codexDir := filepath.Join(root, ".codex")
	require.NoError(t, os.MkdirAll(codexDir, 0o755))
	userContent := "[model]\nprovider = \"anthropic\"\nmodel_id = \"claude-sonnet-4-20250514\"\n\n"
	require.NoError(t, os.WriteFile(filepath.Join(codexDir, "config.toml"), []byte(userContent), 0o644))

	require.NoError(t, Generate(root, []string{"codex"}, true))

	result, err := os.ReadFile(filepath.Join(codexDir, "config.toml"))
	require.NoError(t, err)

	s := string(result)
	// User content should be preserved.
	assert.Contains(t, s, `provider = "anthropic"`)
	// Managed section should be added.
	assert.Contains(t, s, "# BEGIN slipway agents")
	assert.Contains(t, s, "[agents.slipway-executor]")
}

func TestConfigTOMLPartialMarkersError(t *testing.T) {
	root := t.TempDir()
	t.Setenv("CODEX_HOME", t.TempDir())

	codexDir := filepath.Join(root, ".codex")
	require.NoError(t, os.MkdirAll(codexDir, 0o755))

	// Only BEGIN marker, no END — should error.
	broken := "[model]\nprovider = \"anthropic\"\n\n# BEGIN slipway agents\n[agents.slipway-old]\n"
	require.NoError(t, os.WriteFile(filepath.Join(codexDir, "config.toml"), []byte(broken), 0o644))

	err := Generate(root, []string{"codex"}, true)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "incomplete slipway markers")
}

func TestCursorNoAgents(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"cursor"}, true))

	// No agent directory should be created for Cursor.
	agentsDir := filepath.Join(root, ".cursor", "agents")
	_, err := os.Stat(agentsDir)
	assert.True(t, os.IsNotExist(err), "cursor should not have agents directory")
}

func TestCodexNoProjectLocalCommands(t *testing.T) {
	root := t.TempDir()
	t.Setenv("CODEX_HOME", t.TempDir())
	require.NoError(t, Generate(root, []string{"codex"}, true))

	// No commands directory should be created.
	commandsDir := filepath.Join(root, ".codex", "commands")
	_, err := os.Stat(commandsDir)
	assert.True(t, os.IsNotExist(err), "codex should not have project-local commands")
}

func TestOpenCodeNestedCommands(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"opencode"}, true))

	// OpenCode should use nested command paths.
	path := filepath.Join(root, ".opencode", "commands", "slipway", "new.md")
	_, err := os.Stat(path)
	assert.NoError(t, err, "opencode should have nested command paths")
}

func TestCodexGlobalPrompts(t *testing.T) {
	root := t.TempDir()
	codexHome := t.TempDir()
	t.Setenv("CODEX_HOME", codexHome)

	require.NoError(t, Generate(root, []string{"codex"}, true))

	// Prompt files should be generated at $CODEX_HOME/prompts/.
	promptPath := filepath.Join(codexHome, "prompts", "slipway-new.md")
	content, err := os.ReadFile(promptPath)
	require.NoError(t, err)

	s := string(content)
	// Check frontmatter.
	assert.Contains(t, s, "description:")
	assert.Contains(t, s, "argument-hint:")
	// Check $ARGUMENTS usage.
	assert.Contains(t, s, "$ARGUMENTS")
	// Check it references the right skill.
	assert.Contains(t, s, "slipway-new")

	// Verify all command IDs have prompt files.
	for _, id := range commandIDs() {
		path := filepath.Join(codexHome, "prompts", "slipway-"+id+".md")
		_, err := os.Stat(path)
		assert.NoError(t, err, "missing codex prompt for %s", id)
	}

	// Verify refresh protection.
	require.NoError(t, os.WriteFile(promptPath, []byte("custom"), 0o644))
	require.NoError(t, Generate(root, []string{"codex"}, false))
	customContent, _ := os.ReadFile(promptPath)
	assert.Equal(t, "custom", string(customContent), "prompt should not be overwritten without refresh")

	// Verify refresh overwrites.
	require.NoError(t, Generate(root, []string{"codex"}, true))
	refreshedContent, _ := os.ReadFile(promptPath)
	assert.NotEqual(t, "custom", string(refreshedContent), "prompt should be overwritten with refresh")
}

func TestByteStabilityAllTools(t *testing.T) {
	for _, toolID := range []string{"claude", "codex", "cursor", "gemini", "opencode"} {
		t.Run(toolID, func(t *testing.T) {
			root := t.TempDir()
			t.Setenv("CODEX_HOME", t.TempDir())
			require.NoError(t, Generate(root, []string{toolID}, true))

			// Collect all generated files.
			files := map[string][]byte{}
			err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
				if err != nil || info.IsDir() {
					return err
				}
				rel, _ := filepath.Rel(root, path)
				content, readErr := os.ReadFile(path)
				if readErr != nil {
					return readErr
				}
				files[rel] = content
				return nil
			})
			require.NoError(t, err)

			// Regenerate and compare.
			require.NoError(t, Generate(root, []string{toolID}, true))
			err = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
				if err != nil || info.IsDir() {
					return err
				}
				rel, _ := filepath.Rel(root, path)
				content, readErr := os.ReadFile(path)
				if readErr != nil {
					return readErr
				}
				original, exists := files[rel]
				assert.True(t, exists, "new file appeared on second generation: %s", rel)
				if exists {
					assert.Equal(t, string(original), string(content), "file %s not byte-stable", rel)
				}
				return nil
			})
			require.NoError(t, err)
		})
	}
}

func TestGeneratedGovernanceSkillsHaveMinimalFrontmatter(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"claude"}, true))

	routingFields := []string{
		"required_levels:", "state:", "type:", "skill_name:",
		"guardrail_required:", "closeout_conditional:",
		"reviewer_independent:", "run_summary_bound:", "mitigation_target:",
	}

	allStaticGov := append([]string{}, GovernanceSkillNames...)
	allStaticGov = append(allStaticGov, standaloneGovernanceNames...)
	for _, name := range allStaticGov {
		path := filepath.Join(root, ".claude", "skills", "slipway", name, "SKILL.md")
		content, err := os.ReadFile(path)
		require.NoError(t, err, "failed to read %s", name)
		s := string(content)

		// Extract frontmatter between --- markers.
		parts := splitFrontmatter(s)
		require.Len(t, parts, 3, "%s missing frontmatter", name)
		fm := parts[1]
		assert.Contains(t, fm, "name:", "%s missing name", name)
		assert.Contains(t, fm, "description:", "%s missing description", name)
		for _, field := range routingFields {
			assert.NotContains(t, fm, field, "%s frontmatter has routing field %s", name, field)
		}
	}

	for _, name := range TemplatedGovernanceSkillNames {
		path := filepath.Join(root, ".claude", "skills", "slipway", name, "SKILL.md")
		content, err := os.ReadFile(path)
		require.NoError(t, err, "failed to read %s", name)
		s := string(content)
		parts := splitFrontmatter(s)
		require.Len(t, parts, 3, "%s missing frontmatter", name)
		fm := parts[1]
		assert.Contains(t, fm, "name:", "%s missing name", name)
		assert.Contains(t, fm, "description:", "%s missing description", name)
		// wave-orchestration is tool-aware; the 4 converted governance skills
		// use Render for partial support but are tool-independent.
		if name == "wave-orchestration" {
			assert.Contains(t, fm, "tool:", "%s missing tool", name)
		}
		for _, field := range []string{"required_levels:", "state:", "type:", "mitigation_target:", "run_summary_bound:"} {
			assert.NotContains(t, fm, field, "%s frontmatter has routing field %s", name, field)
		}
	}
}

func TestGeneratedAdapterAndStandaloneSkillsHaveFrontmatterDescriptions(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"claude"}, true))

	for _, name := range adapterSkillIDs {
		path := filepath.Join(root, ".claude", "skills", "slipway", name, "SKILL.md")
		content, err := os.ReadFile(path)
		require.NoError(t, err, "failed to read %s", name)
		parts := splitFrontmatter(string(content))
		require.Len(t, parts, 3, "%s missing frontmatter", name)
		fm := parts[1]
		assert.Contains(t, fm, "name:", "%s missing name", name)
		assert.Contains(t, fm, "description:", "%s missing description", name)
		assert.Contains(t, fm, "tool:", "%s missing tool", name)
	}

	for _, name := range standaloneNames {
		path := filepath.Join(root, ".claude", "skills", "slipway", name, "SKILL.md")
		content, err := os.ReadFile(path)
		require.NoError(t, err, "failed to read %s", name)
		parts := splitFrontmatter(string(content))
		require.Len(t, parts, 3, "%s missing frontmatter", name)
		fm := parts[1]
		assert.Contains(t, fm, "name:", "%s missing name", name)
		assert.Contains(t, fm, "description:", "%s missing description", name)
		for _, field := range []string{"state:", "type:", "required_levels:", "mitigation_target:", "run_summary_bound:"} {
			assert.NotContains(t, fm, field, "%s frontmatter has retired field %s", name, field)
		}
	}
}

func TestDoneSkillDocumentsAllReadyAcrossActiveExecutions(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"claude"}, true))

	content, err := os.ReadFile(filepath.Join(root, ".claude", "skills", "slipway", "done", "SKILL.md"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "`--all-ready` archives every active change that is currently done-ready.")
}

func TestGeneratedAgentsHaveNoRoutingFrontmatter(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	require.NoError(t, Generate(root, []string{"claude"}, true))

	entries, err := os.ReadDir(filepath.Join(root, ".claude", "agents"))
	require.NoError(t, err)

	for _, e := range entries {
		if e.IsDir() || !isAgentFile(e.Name()) {
			continue
		}
		path := filepath.Join(root, ".claude", "agents", e.Name())
		content, err := os.ReadFile(path)
		require.NoError(t, err)
		parts := splitFrontmatter(string(content))
		if len(parts) < 3 {
			continue
		}
		fm := parts[1]
		assert.NotContains(t, fm, "state:", "%s frontmatter has state field", e.Name())
		assert.NotContains(t, fm, "type:", "%s frontmatter has type field", e.Name())
		assert.Contains(t, fm, "name:", "%s missing name", e.Name())
		assert.Contains(t, fm, "description:", "%s missing description", e.Name())
	}
}

func splitFrontmatter(content string) []string {
	// Split on "---" preserving the text between first two markers.
	i := 0
	for i < len(content) && content[i] == '\n' {
		i++
	}
	if i < len(content)-3 && content[i:i+3] == "---" {
		rest := content[i+3:]
		end := -1
		for j := 0; j < len(rest); j++ {
			if j == 0 || rest[j-1] == '\n' {
				if len(rest[j:]) >= 3 && rest[j:j+3] == "---" {
					end = j
					break
				}
			}
		}
		if end >= 0 {
			return []string{content[:i], rest[:end], rest[end+3:]}
		}
	}
	return []string{content}
}

func commandSurfacePath(root, codexHome string, cfg ToolConfig, id string) (string, string) {
	if cfg.PromptsStyle == "global" {
		rel := filepath.ToSlash(filepath.Join("prompts", "slipway-"+id+".md"))
		return rel, filepath.Join(codexHome, filepath.FromSlash(rel))
	}

	ext := ".md"
	if cfg.CommandFormat == "toml" {
		ext = ".toml"
	}
	var rel string
	switch cfg.CommandStyle {
	case "flat":
		rel = filepath.ToSlash(filepath.Join(cfg.CommandsDir, "slipway-"+id+ext))
	default:
		rel = filepath.ToSlash(filepath.Join(cfg.CommandsDir, "slipway", id+ext))
	}
	return rel, filepath.Join(root, filepath.FromSlash(rel))
}

func assertHookCommandRegistered(t *testing.T, settingsPath, eventName, command string) {
	t.Helper()

	content, err := os.ReadFile(settingsPath)
	require.NoError(t, err)

	settings := map[string]any{}
	require.NoError(t, json.Unmarshal(content, &settings))

	hooks, ok := settings["hooks"].(map[string]any)
	require.True(t, ok, "settings missing hooks object")

	entries, ok := hooks[eventName].([]any)
	require.True(t, ok, "settings missing hook event %s", eventName)

	found := false
	for _, entry := range entries {
		entryMap, ok := entry.(map[string]any)
		if !ok {
			continue
		}
		rawHooks, ok := entryMap["hooks"].([]any)
		if !ok {
			continue
		}
		for _, hook := range rawHooks {
			hookMap, ok := hook.(map[string]any)
			if ok && hookMap["command"] == command {
				found = true
				break
			}
		}
		if found {
			break
		}
	}
	assert.True(t, found, "expected %s to register hook command %q", settingsPath, command)
}

func isAgentFile(name string) bool {
	return len(name) > 3 && name[len(name)-3:] == ".md"
}
